spark_dbt:
  target: prod
  outputs:
    dev:
      type: spark
      method: thrift
      host: localhost
      port: 10000
      schema: cliente_5037
      connect_timeout: 60
      connect_retries: 5
    prod:
      type: spark
      method: session
      schema: default
      host: NA
    docs:
      type: spark
      method: session
      schema: cliente_{{ var('cliente_id', 'juca') }}
      host: NA

